FROM node:20.11.0-alpine as build

WORKDIR /app
COPY package.json /app
RUN npm install

FROM python:3.10

COPY . app
WORKDIR /app

COPY --from=build /app /app

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

EXPOSE 8080
ENV PORT 8080

CMD ["python", "manage.py", "runserver", "127.0.0.1:8000"]

