# Generated by Django 5.0.1 on 2024-08-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_task_contributorids_remove_task_lasteditor_and_more"),
        ("apiTasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="taskID",
            field=models.ForeignKey(
                on_delete=models.SET("DELETED_PROFILE"), to="apiTasks.task"
            ),
        ),
        migrations.DeleteModel(
            name="Task",
        ),
    ]
