# Generated by Django 5.0.1 on 2024-08-18 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_feedback_taskid_delete_task"),
        ("apiProjects", "0001_initial"),
        ("apiTasks", "0003_alter_task_lasteditor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="profileID",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="projectID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="apiProjects.project"
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="taskID",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="apiTasks.task",
            ),
        ),
    ]
