# Generated by Django 5.0.1 on 2024-07-31 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiAccounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="password",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
